[project]
name = "bearings"
version = "0.0"
requires-python = ">= 3.8"
authors = [
  {name = "c-mcst"}
]
description = "A small library for working with geographical bearing lines."
readme = "README.md"
license = {file = "LICENSE"}

[tool.setuptools]
packages = ["bearings"]